### ISSUE TITLE
Weather API Key Leak

### ISSUE THREAD

**Issue by Infinixius** [virejdasani/LuminousNewTab#16]
Your API key for https://weatherapi.com can very easily be extracted by downloading a GitHub release, opening the zip, and heading to `assets/config.json`.
![image](https://user-images.githubusercontent.com/68125679/137589576-fb2ec1d3-24f0-478e-a30c-b978ca79fc28.png)

I don't think there's an easy way to fix this. You could try hosting your own server on something like [Heroku](https://dashboard.heroku.com) and having that connect to https://weatherapi.com and return the results to the extension.

**Comment by virejdasani** [comment]
Done! Thanks again :)
